Lesson 6
IvanKOS7/qna pull request #3
Opened 2022-05-23 12:00 UTC by IvanKOS7

2022-05-31 11:06 UTC, russo-matrosso commented on app/controllers/answers_controller.rb
> +    if @answer.author == current_user
Лучше сравнивать по id, чтобы не делать дополнительный запрос в базу

2022-05-31 11:06 UTC, russo-matrosso commented on app/controllers/answers_controller.rb
> +#test me
Протестировано в итоге или нет? 
Не забывай чистить код перед сдачей

2022-05-31 11:06 UTC, russo-matrosso commented on app/controllers/answers_controller.rb
> +      { alert: 'You have not right to delete Answer'}
А что делает эта строка? Редиректа никуда нет, для пользователя ничего не произойдет

2022-05-31 11:06 UTC, russo-matrosso commented on app/controllers/questions_controller.rb
> +
Лишняя пустая строка перед before_action

2022-05-31 11:06 UTC, russo-matrosso commented on app/controllers/questions_controller.rb
>      @question = Question.new(question_params)
А какой будет автор у вопроса?

2022-05-31 11:06 UTC, russo-matrosso commented on app/models/answer.rb
> +  belongs_to :author, class_name: "User", optional: true
Я бы сделал автора обязательным, иначе будет много проблем

2022-05-31 11:06 UTC, russo-matrosso commented on spec/controllers/questions_controller_spec.rb
>    describe 'POST #create' do
Стоит протестировать что вопросы и ответы создаются с правильным автором

2022-05-31 11:06 UTC, russo-matrosso commented on spec/factories/questions.rb
> +
Стоит также добавить автора в фабрику

2022-06-01 07:43 UTC, russo-matrosso commented on app/controllers/answers_controller.rb
>      @answer = @question.answers.new
в одну строку -  `@question.answers.new(author: current_user)`

2022-06-01 07:43 UTC, russo-matrosso commented on app/controllers/answers_controller.rb
> +    if @answer.author.id == current_user.id
все равно подгружается пользователь
`if @answer.author_id == current_user.id`

2022-06-01 07:43 UTC, russo-matrosso commented on spec/factories/questions.rb
> +    trait :with_author do
Если у нас пользователь обязателен -стоит его добавить не trait, а в основную фабрику

2022-06-01 08:23 UTC, vkurennov requested changes

2022-06-01 08:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.author.id == current_user.id
да, смысл сравнения по id в том, чтобы не делать лишний запрос к бд. а еще лучше вынести эту проверку в метод `User#author_of?` и использовать этот метод везде, где нужна такая проверка

2022-06-01 08:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:question_id, :body)
question_id не внутри answer передается, а просто в params, поэтому здесь его указывать не нужно

2022-06-01 08:23 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.author == current_user
замени на вызов `User#author_of?`

2022-06-01 08:23 UTC, vkurennov commented on app/views/questions/index.html.slim
> +div class="questions"
в slim, если нужен div c классом, есть короткий синтаксис:

`.questions`

2022-06-01 08:23 UTC, vkurennov commented on app/views/answers/_form.html.slim
> += fields_for :answer, @question.answers.new, local: true do |f|
нужен вывод ошибок валидации

2022-06-01 08:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
>      if @answer.save
в ветке else нужно рендерить questions/show, т.е. страницу с формой, чтобы отобразить ошибки валидации

2022-06-01 08:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def index
index, new и show для ответов вообще не нужны, т.к. список ответов и форма у нас на странице questions/show

2022-06-01 08:23 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.author == current_user
и что должно произойти, если условие не выполнится?

2022-06-01 08:23 UTC, vkurennov commented on app/views/questions/index.html.slim
> +  = content_tag :h1, 'Questions list'
просто:

`h1 Questuon list`

2022-06-01 08:23 UTC, vkurennov commented on app/views/questions/show.html.slim
> +div class="question"
`.question`

2022-06-01 08:23 UTC, vkurennov commented on config/database.yml
>  development:
database.yml обычно не включают в репозиторий, т.к. на разных машинах могут быть разные настройки подключений. и даже если ты разрабатываешь один, на проде точно будут другие настройки

2022-06-01 08:23 UTC, vkurennov commented on config/routes.rb
>      resources :answers
ресурс answers стоит объявить shallow, чтобы не передавать question_id там, где он не нужен, например, для destroy

2022-06-01 08:23 UTC, vkurennov commented on spec/features/question/index_spec.rb
> +        expect(page).to have_css('.questions')
это не гарантирует, что ответы реально отображаются на странице. лучше всего сам текст ответов проверить, но либо тогда с указанием кол-ва на странице, либо сделав ответы разными через sequence в фабриках

2022-06-01 08:23 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +feature 'User can view question and question answers', %q{
привязываться к классам, не проверяя содеражние страницы - так себе идея. фича-тесты пишутся как бы с т.з. пользователя. представь, что этот сценарий будет выполнять живой тестер, ты же не будешь ему писать "зайди на страницу и проверь, что такой-то css-класс там есть". даже если и есть, это никак не проверяет, а есть ли там нужный контент

2022-06-01 08:23 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +      scenario 'User create answer of question inline' do
создание ответа - это вообще отдельная фича (в отдельном файле) со своими сценариями. мы не страницы как таковые тестируем, а именно фичи, т.е. некоторые возможности системы

2022-06-26 09:26 UTC, merged